[Binapi] introduce NWI binary API for UPG plugin
travelping/upg-vpp pull request #203
Opened 2021-12-10 08:26 UTC by sergeymatov

2021-12-10 11:01 UTC, ivan4th requested changes

2021-12-10 11:01 UTC, ivan4th commented on test/e2e/upg_e2e.go
> +	ginkgo.Context("NWI binapi", func() {
`"for NWIs"`

2021-12-10 11:01 UTC, ivan4th commented on test/e2e/upg_e2e.go
> +		ginkgo.It("Check nwi binapi functions", func() {
`"adds, removes and lists the NWIs"`

2021-12-13 17:45 UTC, sergeymatov commented on test/e2e/upg_e2e.go
> +
done

2021-12-13 17:45 UTC, sergeymatov commented on upf/upf.c
> + */
done

2021-12-13 17:46 UTC, sergeymatov commented on upf/upf.api
> +  u32 vrf;
Adjusted api message structure with `ip[46]_table_id` and some logic around it inside UPG

2021-12-13 17:46 UTC, sergeymatov commented on test/e2e/upg_e2e.go
> +		ginkgo.It("Check policy binapi functions", func() {
thanks, fixed

2021-12-13 17:46 UTC, sergeymatov commented on test/e2e/upg_e2e.go
> +	ginkgo.Context("NWI binapi", func() {
fixed

2021-12-13 17:46 UTC, sergeymatov commented on test/e2e/upg_e2e.go
> +		ginkgo.It("Check nwi binapi functions", func() {
done

2021-12-14 12:37 UTC, ivan4th approved these changes
LGTM

2021-12-14 12:45 UTC, merged