switch to UPF specific timer wheel implementation
travelping/upg-vpp pull request #341
Opened 2023-06-19 11:10 UTC by RoadRunnr

2023-06-20 13:29 UTC, ivan4th requested changes
One quite small change might be needed, also there's typo in one of the commit descriptions ("stoped"):

> Handles must now be allocated before they can be started and they are not
longer automatically freed when stoped. Reusing handles for restarting
or changing timer is now possible.

should be

> Handles must now be allocated before they can be started and are no
longer automatically freed when stopped. Reusing handles for restarting
or changing the timer is now possible.

2023-06-20 15:49 UTC, RoadRunnr commented on upf/upf_pfcp_server.c
> +	TW (tw_timer_expire_timers_vec) (&psm->timer, psm->now, psm->expired);
done

2023-06-20 16:30 UTC, ivan4th approved these changes

2023-06-20 16:31 UTC, ivan4th requested changes
Almost approved, but there's a checkstyle error
```
Files upf/upf_pfcp_server.c and upf/upf_pfcp_server.c.out2 differ

Checkstyle failed for upf/upf_pfcp_server.c.
Run indent (twice!) as shown to fix the problem:
indent upf/upf_pfcp_server.c
indent upf/upf_pfcp_server.c
*******************************************************************
* VPP CHECKSTYLE FAILED
* CONSULT FAILURE LOG ABOVE
* NOTE: Running 'hack/checkstyle.sh --fix' *MAY* fix the issue
*******************************************************************
make: *** [Makefile:29: checkstyle] Error 1
```

2023-06-21 06:42 UTC, ivan4th approved these changes
LGTM

2023-06-21 07:28 UTC, merged