feat: timers missed metric
travelping/upg-vpp pull request #357
Opened 2023-10-12 20:07 UTC by demo-exe

2023-10-13 06:00 UTC, mgumz commented
"feat: add metric 'upf_timers_missed'

this commit adds the metric 'upf_timers_missed' to make the issue visible without relying to scraping logs.
"

2023-10-20 09:52 UTC, mogaika requested changes

2023-10-23 20:26 UTC, demo-exe commented on upf/upf.h
> +  _(TIMERS_MISSED, timers_missed, upf) \
whoops, good catch

2023-10-23 20:27 UTC, demo-exe commented on upf/upf.h
```suggestion
  _(FLOWS_STITCHED_DIRTY_FIFOS, stitched_dirty_fifos, upf) \
  _(TIMERS_MISSED, timers_missed, upf)

```

2023-10-24 08:53 UTC, mogaika approved these changes

2023-11-07 15:55 UTC, merged