upg-vpp-xdp
travelping/upg-vpp pull request #64
Opened 2021-01-11 13:17 UTC by sergeymatov

Based on 20-09 stable branch of vpp (Dec 2020)

2021-01-11 13:55 UTC, RoadRunnr commented
some of the build system changes seem to be related to the use of the old 18.04 Ubuntu LTS release. VPP 20.09 support the 20.04 LTS release and I think we should switch to that.

2021-01-22 08:06 UTC, sergeymatov commented
@RoadRunnr @ivan4th 
Please take a look on this request again
It has several successful e2e test runs with both xdp/af_packet

2021-01-22 12:00 UTC, ivan4th requested changes

2021-01-25 08:29 UTC, sergeymatov commented on test/e2e/framework/framework.go
> +		}*/
Yes, fixed

2021-01-25 08:30 UTC, sergeymatov commented on test/e2e/framework/upgmode.go
> +				MTU: 1464,
Added in a vpp constants set

2021-01-25 08:33 UTC, sergeymatov commented on test/e2e/upg_e2e.go
> +		f.GTPUMTU = 1460
Constant fixed
I suppose  we have to check max XDP MTU, added a TODO for this

2021-01-25 08:33 UTC, sergeymatov commented on test/e2e/vpp/vpp.go
> +	DEFAULT_MTU             = 1500
Constant added

2021-01-25 08:50 UTC, RoadRunnr commented on test/e2e/upg_e2e.go
> +		f.GTPUMTU = 1460
> Constant fixed
> I suppose we have to check max XDP MTU, added a TODO for this

found that [her](https://people.netfilter.org/hawk/presentations/ebplane2019/xdp-bpf-building-blocks.pdf)
`XDP max MTU: 3520 bytes (page_size(4096) - headroom(256) - shinfo(320))`

2021-02-10 11:56 UTC, ivan4th commented
LGTM. There are some quirks in the "MTU corner cases" e2e test case but I will try to fix it myself in a followup.

2021-02-12 11:07 UTC, RoadRunnr approved these changes

2021-02-12 21:01 UTC, ivan4th approved these changes

2021-02-12 21:01 UTC, merged